Singleton neo4j
stellasia/neomap pull request #79
Opened 2020-09-06 19:02 UTC by jodom

A singleton neo4jService that encapsulates driver. Layers don't need to have a knowledge of underlying neo4j driver. Composition proposed here allows us to smoothly swap out drivers in future #65, and remove driver instantiation on critical boot path #78.
Additionally, this PR formalizes a result API on neo4jService endpoints. Success from service calls return as `{ status: 200, result: someResult }` while failures return `{ status: 500, error: errorWithStack }`

Next: This pattern opens up an opportunity for better error ux, most immediately, a path for solving #77 [ don't rerender if we hit error on create/update new layer ]

PS: Builds on top of changes in PR #75

2020-09-06 19:02 UTC, jodom commented
cc @wagnerjt for reviews on service changes

2020-09-08 15:01 UTC, jodom commented
Not ready until I add tests for the driver... :)

2020-09-12 23:42 UTC, jodom commented
> Not ready until I add tests for the driver... :)

done. @stellasia, @wagnerjt I'd love your reviews on pr

2020-11-21 20:10 UTC, jodom commented
> Not ready until I add tests for the driver... :)

resolved. Tests covering singleton driver pattern are in place

2020-11-21 20:11 UTC, jodom commented
> A singleton neo4jService that encapsulates driver. Layers don't need to have a knowledge of underlying neo4j driver. Composition proposed here allows us to smoothly swap out drivers in future #65, and remove driver instantiation on critical boot path #78.
> Additionally, this PR formalizes a result API on neo4jService endpoints. Success from service calls return as `{ status: 200, result: someResult }` while failures return `{ status: 500, error: errorWithStack }`
> 
> Next: This pattern opens up an opportunity for better error ux, most immediately, a path for solving #77 [ don't rerender if we hit error on create/update new layer ]
> 
> PS: Builds on top of changes in PR #75

@stellasia, let's review and close this PR when possible.

2020-11-22 18:03 UTC, stellasia commented
Sure, will do during the coming week!

2020-11-29 10:05 UTC, stellasia requested changes
I found a couple of other bugs when reviewing but not related to this PR. So looks good to me when the issue with `records` is fixed (see comment in code)

2020-12-05 05:15 UTC, jodom commented on src/services/neo4jService.js
> +      (records) => records,
Oh. I even wrote UTs reflecting a flatter result object. Fixed!

2020-12-05 11:13 UTC, stellasia approved these changes

2020-12-05 11:14 UTC, stellasia commented
Thank you very much for this @jodom , merging :100:

2020-12-05 11:14 UTC, merged